project:
  type: website
  output-dir: _site
  resources:
    - LICENSE
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - CHANGELOG.md
    - README.md

website:
  title: "wordguess"
  site-url: https://github.com/UBC-MDS/wordguess
  description: "A Python package with essential functions for a word-guessing game, inspired by Wordle."

  # TOP BAR (Navbar)
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Reference"
        href: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/UBC-MDS/wordguess
        aria-label: GitHub

  # SIDE BAR (Table of Contents & Navigation)
  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - text: "Overview"
        href: index.qmd
      - text: "API Reference"
        href: reference/index.qmd
      - text: "Changelog"
        href: CHANGELOG.md
      - text: "Contributing Guide"
        href: CONTRIBUTING.md
      - text: "Code of Conduct"
        href: CODE_OF_CONDUCT.md
      - text: "License"
        href: LICENSE

# Link the auto-generated styles and sidebar from quartodoc
metadata-files:
  - reference/_sidebar.yml

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
      - reference/_styles-quartodoc.css
    toc: true
    code-copy: true
    code-line-numbers: true

quartodoc:
  package: wordguess
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css

  sections:
    - title: Core functions
      contents:
        - get_n_guesses.get_n_guesses
        - get_result.get_result
        - get_score.get_score
        - result_to_pattern.result_to_pattern
        